title: âœŠ @nti1984
description: âœŠ æå«éšç§å’Œè‡ªç”±
theme: just-the-docs

url: https://anti1984.github.io

# gem: [jekyll-admin]

# Aux links for the upper right navigation
aux_links:
  "ğŸ‘‰ äº¤æµ ":
    - "//twitter.com/_anti1984"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false